export const storeDocObj_1 = {
	storeName: "TomTakes",
	storeDesc: "Artisan Cakes",
	storeLogo: "https://cdn.pixabay.com/photo/2018/07/01/19/50/muffin-3510308_1280.jpg",
	//isAvailable	    : true,
	availabilityStart: "2021-04-02",
	availabilityEnd: "2021-04-05",
	bakeSaleDesc: "",
	bakeSalePromo: "",
	deliveryBool: false,
	deliveryDetails: "",
	selfCollectionBool: true,
	selfCollectionDetails: "Near Dakota MRT",
	email: "testEmail@gmail.com",
	phoneNum: "12345678",
	teleHandle: "",
	instaLink: "",
	fbLink: "",
	websiteLink: "https://www.google.com/",
	storeOwnerID: "user_0001",
	// storeReviews	        : SUBCOLLECTION,
	// storeBakes	        : SUBCOLLECTION,
};

export const storeDocObj_2 = {
	storeName: "bobBakes",
	storeDesc: "We sell freshly baked pastry",
	storeLogo: "https://cdn.pixabay.com/photo/2018/07/20/14/02/grapes-3550733_1280.jpg",
	//isAvailable	    : true,
	availabilityStart: "2021-07-08",
	availabilityEnd: "2021-08-08",
	bakeSaleDesc: "Mothers' Day Sale",
	bakeSalePromo: "Buy $20 worth of bakes and get a free cookie",
	deliveryBool: true,
	deliveryDetails: "North-south region of SG",
	selfCollectionBool: true,
	selfCollectionDetails: "Near MRTS, Buona Vista preferably",
	email: "testEmail@gmail.com",
	phoneNum: "",
	teleHandle: "",
	instaLink: "",
	fbLink: "",
	websiteLink: "",
	storeOwnerID: "user_0001",
	// storeReviews	        : SUBCOLLECTION,
	// storeBakes	        : SUBCOLLECTION,
};

export const storeDocObj_3 = {
	storeName: "codCakes",
	storeDesc: "fishy fishy business",
	storeLogo:
		"https://images.pexels.com/photos/2127969/pexels-photo-2127969.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
	//isAvailable	    : true,
	availabilityStart: "2021-01-01",
	availabilityEnd: "2021-12-25",
	bakeSaleDesc: "",
	bakeSalePromo: "",
	deliveryBool: true,
	deliveryDetails: "Choa Chu Kang",
	selfCollectionBool: true,
	selfCollectionDetails: "Near Choa Chu Kang MRT",
	email: "fishybusiness@gmail.com",
	phoneNum: "",
	teleHandle: "",
	instaLink: "",
	fbLink: "",
	websiteLink: "",
	storeOwnerID: "user_0001",
	// storeReviews	        : SUBCOLLECTION,
	// storeBakes	        : SUBCOLLECTION,
};
